volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kittygram_user -d kittygram" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    image: orbitiumnos/kittygram_backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/static
      - media:/app/media

  frontend:
    image: orbitiumnos/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: orbitiumnos/kittygram_gateway
    env_file: .env
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/app/media
