#cloud-config
ssh_pwauth: false

users:
  - name: ${SSH_USER}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo, docker
    ssh_authorized_keys:
      - ${SSH_KEY}

write_files:
  - path: /root/vm_prep.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -euxo pipefail

      export DEBIAN_FRONTEND=noninteractive

      apt-get update
      apt-get install -y ca-certificates curl gnupg

      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc

      . /etc/os-release

      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $VERSION_CODENAME stable" > /etc/apt/sources.list.d/docker.list

      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      systemctl enable --now docker

      usermod -aG docker ${SSH_USER}

      mkdir -p /home/${SSH_USER}/kittygram
      chown -R ${SSH_USER}:${SSH_USER} /home/${SSH_USER}/kittygram

runcmd:
  - bash /root/vm_prep.sh